### PR TITLE
<feature Bullet Events Implemented

### PR DESCRIPTION
**Pull request by AlmaVL**
- Alien Shoot
- Spaceship shoot
- Bullet creation
- Alien bullet offscreen
- Spaceship bullet offscreen

### CODE REVIEW

**Comment by JerPk** [comment]
I've added some comments to commit e3e9ed3, after changing that it can be merged.
Btw I think it is not needed to push the "logfile.txt" to the repository.

**Comment by AlmaVL** [comment]
Fixed all comments.

**Comment by JerPk** [comment]
When a second person has checked it, it can be merged.

**Comment by Mari3** [comment]
When an alien or the spaceship shoots, it's supposed to be logged in the shoot methods of spaceship and alien, not the methods from the Bullet class. You can see by looking at the sentences written in the log file that that's not how they were designed.

**Comment by AlmaVL** [comment]
That's how it was implemented. I implemented the shoot log in the spaceship class and the alien class, you can see it the tab called "files changed"
That also why the branch is called "Bullet events" and not "BulletClass"

**Comment by Mari3** [comment]
Oh ok, then the word "bullet" after everything should be removed. It's the spaceship that shoots and not a spaceship bullet.

**Pull request merged**
